"""make widgets user_id not null

Revision ID: 02aa7e61713a
Revises: c5336e6a41d5
Create Date: 2026-04-27 15:54:15.118944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02aa7e61713a'
down_revision: Union[str, Sequence[str], None] = 'c5336e6a41d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM widgets WHERE user_id IS NULL")
    op.alter_column('widgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
