"""add news_feeds and news_articles tables

Revision ID: 0899255d7d07
Revises: 02aa7e61713a
Create Date: 2026-04-28 23:57:44.931511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0899255d7d07'
down_revision: Union[str, Sequence[str], None] = '02aa7e61713a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE widget_type ADD VALUE IF NOT EXISTS 'news'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_key', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('feed_url', sa.String(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_feeds_feed_key'), 'news_feeds', ['feed_key'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['news_feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_news_feeds_feed_key'), table_name='news_feeds')
    op.drop_table('news_feeds')
    # ### end Alembic commands ###
