"""move summary to cluster, drop article summary columns

Revision ID: 64c6ba48a9aa
Revises: ee3945059e8c
Create Date: 2026-05-01 10:33:18.929707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64c6ba48a9aa'
down_revision: Union[str, Sequence[str], None] = 'ee3945059e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_clusters', sa.Column('summary', sa.String(), nullable=True))
    op.drop_column('news_articles', 'summary_generated_at')
    op.drop_column('news_articles', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('summary_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('article_clusters', 'summary')
    # ### end Alembic commands ###
