"""add summary to price_snapshots

Revision ID: 6bc3f437a53e
Revises: 64c6ba48a9aa
Create Date: 2026-05-03 21:21:45.920584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc3f437a53e'
down_revision: Union[str, Sequence[str], None] = '64c6ba48a9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_snapshots', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('price_snapshots', sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_snapshots', 'summary_updated_at')
    op.drop_column('price_snapshots', 'summary')
    # ### end Alembic commands ###
