"""add_widgets_table

Revision ID: a32d37208a59
Revises: c9823b19d829
Create Date: 2026-04-23 18:38:57.627672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a32d37208a59'
down_revision: Union[str, Sequence[str], None] = 'c9823b19d829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('asset', 'time', name='widget_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layout_x', sa.Integer(), nullable=False),
    sa.Column('layout_y', sa.Integer(), nullable=False),
    sa.Column('layout_w', sa.Integer(), nullable=False),
    sa.Column('layout_h', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widgets')
    # ### end Alembic commands ###
