"""add day_high day_low volume to price_snapshots

Revision ID: e55cbd8eb5b9
Revises: a32d37208a59
Create Date: 2026-04-26 22:24:03.178566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55cbd8eb5b9'
down_revision: Union[str, Sequence[str], None] = 'a32d37208a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_snapshots', sa.Column('day_high', sa.Numeric(), nullable=True))
    op.add_column('price_snapshots', sa.Column('day_low', sa.Numeric(), nullable=True))
    op.add_column('price_snapshots', sa.Column('volume', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_snapshots', 'volume')
    op.drop_column('price_snapshots', 'day_low')
    op.drop_column('price_snapshots', 'day_high')
    # ### end Alembic commands ###
