"""add AI columns and article_clusters table

Revision ID: ee3945059e8c
Revises: 0899255d7d07
Create Date: 2026-04-30 18:41:51.053427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3945059e8c'
down_revision: Union[str, Sequence[str], None] = '0899255d7d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('news_articles', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('news_articles', sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news_articles', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('news_articles', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_news_articles_cluster_id'), 'news_articles', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_news_articles_duplicate_of_id'), 'news_articles', ['duplicate_of_id'], unique=False)
    op.create_foreign_key(None, 'news_articles', 'news_articles', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'news_articles', 'article_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_articles', type_='foreignkey')
    op.drop_constraint(None, 'news_articles', type_='foreignkey')
    op.drop_index(op.f('ix_news_articles_duplicate_of_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_cluster_id'), table_name='news_articles')
    op.drop_column('news_articles', 'duplicate_of_id')
    op.drop_column('news_articles', 'cluster_id')
    op.drop_column('news_articles', 'summary_generated_at')
    op.drop_column('news_articles', 'summary')
    op.drop_table('article_clusters')
    # ### end Alembic commands ###
